### ISSUE TITLE
Power calculation from 3 separate values for L1, L2 and L3 in a 3 phase system

### ISSUE THREAD

**Issue by schneefloh** [pkuehnel/TeslaSolarCharger#284] opened 2022-09-08 15:32 UTC
My Victron CerboGX has no total power output over modbus for the EM24 power meter used for net in/out. I can only get three separate values for L1, L2 and L3 in three successive registers.
Is it possible to add this functionality?

**Comment by pkuehnel** [comment] 2022-09-08 16:37
Are you sure this is not possible? Adding this functionality is quite a big deal.

**Comment by schneefloh** [comment] 2022-09-09 12:07
The Victron modbus register list shows no total value for the power measurement, at least I can't find a suitable register ;-)

**Comment by pkuehnel** [comment] 2022-09-09 12:12
As there are currnetly a few features in the pipeline it will at least take two to three weeks until I can implement this feature. For now I would recommend you to use `3` as Correction factor. As long as you don't have to much power consumption in your house this would still give you pretty good results.

**Comment by pkuehnel** [comment] 2022-09-09 12:14
Using https://docs.victronenergy.com/vrmapi/overview.html#get-all-installations-sites-of-a-given-user is not possible?

**Comment by schneefloh** [comment] 2022-09-09 12:32
Accessing the VRM API seems possible, but I don't want to rely on a web-service.
Unfortunately the simple solution with a factor 3 correction does not work, as the power is not equally distributed over the 3 lines.

**Comment by pkuehnel** [comment] 2022-09-09 12:36
Can you setup something like [Node-RED](https://nodered.org/) or [Home Assistant](https://www.home-assistant.io/) or [Solaranzeige.de](https://solaranzeige.de/)? These are all offline tools.

**Comment by schneefloh** [comment] 2022-09-09 12:42
I already was looking into Node-RED as this should run on docker in my Synology. But I'm new into that and have to do some homework first ;-)
MQTT could be the solution as the Victron Cerbo ha a MQTT interface as well. And this should include the total power values as well.

**Comment by pkuehnel** [comment] 2022-09-09 13:02
You just can change your image tag to `:solarmqtt`. Then you will get two new fields in the configuration for MQTT topic and server:
![7f50de98e2d5204471c4cd65530c04e5c42a3d67_2_1380x762](https://user-images.githubusercontent.com/35361981/189354502-4d5afcfa-b654-4b60-8bc0-dc50563d0ad4.jpeg)

In this early stage MQTT only supports grid power but with release 2.6.0 all other solar values will be supported with MQTT, too. Important: you have to remove the Grid URL, MQTT is only used if grid URL is empty. And in two minutes your CorrectionFactor problem is fixed in the MQTT branch as well...

**Comment by schneefloh** [comment] 2022-09-09 13:47
I think we're almost there! Power (total) is in the MQTT answer:
![Zwischenablage01](https://user-images.githubusercontent.com/113058377/189363930-123ed4c7-3194-4136-8534-7af0db8f7ebd.png)

But just filling in the address "192.168.178.43:1883" and topic "N/48e7da87e455/grid/30/Ac/Power" does not yet give a result:
![Zwischenablage01](https://user-images.githubusercontent.com/113058377/189364953-2b888c16-f8e3-4fd1-97af-ced5a9a8693e.png)

**Comment by pkuehnel** [comment] 2022-09-09 15:46
Could you please restart the container and then send me the logs?

**Comment by schneefloh** [comment] 2022-09-09 18:42
Logfile attached. Seems to get the value over MQTT, but does not show up in the overview:
>[20:31:30.168 VRB TeslaSolarCharger.Server.Services.SolarMqttService] Payload for topic N/48e7da87e455/grid/30/Ac/Power is {"value": -21.0}

[teslasolarcharger.log](https://github.com/pkuehnel/TeslaSolarCharger/files/9537944/teslasolarcharger.log)

**Comment by pkuehnel** [comment] 2022-09-09 18:59
I did not further look into the logs, but the issue is, that the payload is not the value `-21.0` but a Json object `{"value": -21.0}`. I will add the same features with JSON Path as it is implemented for REST APIs. Good for me, that this occurred before I finished the feature. You will get an update in a few hours or tomorrow afternoon.

**Comment by pkuehnel** [comment] 2022-09-10 13:29
Just changed a few other things. Would recommend to update again.

**Comment by pkuehnel** [comment] 2022-09-11 20:20
I will close that issue as it will be resolved with https://github.com/pkuehnel/TeslaSolarCharger/issues/204

**Closed by pkuehnel** 2022-09-11 20:20 UTC
Labels: enhancement, wontfix, UI, Backend

**Comment by schneefloh** [comment] 2022-09-12 06:39
I can confirm that reading grid power on my Victron CerboGX installation now works over MQTT:
![Zwischenablage01](https://user-images.githubusercontent.com/113058377/189586789-cada918a-094b-4155-881d-5128bafad8b6.png)
Used settings:
![Zwischenablage02](https://user-images.githubusercontent.com/113058377/189586824-1eb7e9ea-50c1-4aaf-9824-e5c758338ed7.png)

Unfortunately the connection seems to timeout if I'm not connected to the Victron VRM portal in parallel. Found some information about timeout here:
https://github.com/victronenergy/dbus-mqtt#keep-alive

**Comment by pkuehnel** [comment] 2022-09-19 11:27
@schneefloh If you update again, you should be able to add MQTT Topics for your inverter power, home battery power and home battery soc as well.

**Comment by pkuehnel** [comment] 2022-09-19 15:22
Could you please upload your logfiles and your `baseConfig.json`? Should be in your `teslasolarcharger-configs` folder.

**Comment by schneefloh** [comment] 2022-09-19 18:46
Files attached.
[teslasolarcharger.zip](https://github.com/pkuehnel/TeslaSolarCharger/files/9601556/teslasolarcharger.zip)

**Comment by pkuehnel** [comment] 2022-09-19 22:58
Should be fixed, can you please update again and try? You can update both, HomeBatterySoc and HomeBatteryPower to mqtt. In your configuration only HomeBatteryPower is using MQTT (but probably because of the issue).

**Comment by schneefloh** [comment] 2022-09-20 06:16
Now it's working as expected! Thanks!

**Comment by pkuehnel** [comment] 2022-09-21 19:22
You knwo can go back to `:latest`. Thanks for testing.
