### ISSUE TITLE
Missing Scopes

### ISSUE THREAD

**Issue by DomiSanNo1** [pkuehnel/TeslaSolarCharger#1250] opened 2024-05-25 07:34 UTC
![image](https://github.com/pkuehnel/TeslaSolarCharger/assets/99594547/01372daa-7e8d-4738-bd4d-6203cafbb129)

TSC shows missing scopes. I've already deleted the third-Party-access and generated a new token.

**Comment by S1lncer** [comment] 2024-05-25 08:35
Same here

**Comment by DomiSanNo1** [comment] 2024-05-25 08:43
v12 ⁦(2024.14.3 c939d51f57b4)⁩
Model Y Germany

**Comment by pkuehnel** [comment] 2024-05-25 10:05
Fixed in `v1.25.0`

**Closed** 2024-05-25 10:06 UTC
Labels: bug, backend, prio:critical

**Comment by S1lncer** [comment] 2024-05-25 11:08
> Fixed in `v1.25.0`. Is marked as pre release, because not really tested.

I can confirm this works, the error is no longer showing and the charging of the vehicle works as intended.

**Comment by DomiSanNo1** [comment] 2024-05-25 11:20
It works with integration and App-confirming of a virtual key 👍
Thank you!
