### ISSUE TITLE
Avoid charge start after sunset

### ISSUE THREAD

**Issue by fprucker** [pkuehnel/TeslaSolarCharger#277] opened 2022-09-06 19:20 UTC
Is it possible to avoid that the car charges for 5 minutes when I plug it in at night (after sunset)?

My understanding is that the setting/logic „Time without enough solar power until charging stops (minutes)“ causes this side effect.

**Comment by pkuehnel** [comment] 2022-09-06 19:34
Duplicate of https://github.com/pkuehnel/TeslaSolarCharger/issues/250

**Closed by pkuehnel** 2022-09-06 19:34 UTC
Labels: duplicate

**Comment by pkuehnel** [comment] 2022-09-06 23:37
Will be in the next release. Note: Avoiding charge start is not possible, but stopping right after the first charge setting cycle is possible and will be done in the next release.

**Comment by fprucker** [comment] 2022-09-07 06:33
Great - thank you. Let us know if you need help testing the feature.
