### ISSUE TITLE
Unauthorized Tesla token every ~2 days

### ISSUE THREAD

**Issue by gjuecat** [pkuehnel/TeslaSolarCharger#1125] opened 2024-02-18 07:31 UTC
![Screenshot_20240218_075604_Chrome](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/906318c6-8d90-49a5-9bfc-e50725c85ecd)

Hi,
I get this message approx. every 2-3 days. Is there a solution that the token is authorized for a longer time? Am I the only one with this problem?

Thx
Jürgen

**Comment by pkuehnel** [comment] 2024-02-18 08:23
No, I have the same issue and it looks like this is currently an issue on Tesla's API. Please update to the latest version, I improved logging on that front. When being on the latest version you should find a log `Your token or refresh token is invalid. Very likely you have changed your Tesla password.` And after that a reason from Tesla.

**Comment by pkuehnel** [comment] 2024-02-18 18:04
@gjuecat Try updating to the `:edge` instead of the `:latest` release. I added a workaround: Until now, if Tesla returned an "Unauthorized" Status code one time, TSC immediately deleted the token (as it is unauthorized). Now, the token is not deleted, and it retries forever using the token. Note: The error notification you posted will still be displayed but will be autodeleted if any further Tesla API call returns a success status code.

**Comment by pkuehnel** [comment] 2024-02-18 18:06
But still not sure if it fixes the issue.

**Comment by pkuehnel** [comment] 2024-02-21 17:23
I think I found the cause of the issue; In about 10 minutes there is a new edge release available. Please try with that one again.

**Comment by pkuehnel** [comment] 2024-02-21 18:54
I created a new bug - please update again. Now everything should be fixed.

**Comment by gjuecat** [comment] 2024-02-21 19:44
upgrade edge version again?

**Comment by pkuehnel** [comment] 2024-02-21 20:04
Yes

**Comment by pkuehnel** [comment] 2024-02-22 16:41
As I had this issue a couple of times each day and now it's gone, I release it. This means you can go back to `:latest` in about 15 minutes which will be v 2.24.7. If you still have that issue, feel free to reopen the issue here.

**Closed by pkuehnel** 2024-02-22 16:41 UTC
Labels: bug, backend, prio:critical
